name: Markdown Linter
on:
  pull_request: {}

jobs:
  build:
    name: Install and run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install yarn dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # runs `yarn install`

      - name: Run linter
        uses: borales/actions-yarn@v5
        with:
          cmd: run ci-lint
